module.exports=[{
  title:'yokeneng学院',
  author:'none',
  content:'有可能学院在北京成立'
},
{
  title:'微信公众平台开发',
  author:'yokeneng',
  content:'有可能学院微信公众平台开发课程第一期开学'
},
{
  title:'删除测试',
  author:'somebody',
  content:'微信公众平台开发课程作业'
}]
